/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "TX_1_aliases.h"
#include "TX_1.h"
#include "RX_1_aliases.h"
#include "RX_1.h"
#include "UART_LOG.h"
#include "CAN_Rx.h"
#include "SEVEN_A_aliases.h"
#include "SEVEN_A.h"
#include "SEVEN_B_aliases.h"
#include "SEVEN_B.h"
#include "SEVEN_C_aliases.h"
#include "SEVEN_C.h"
#include "SEVEN_D_aliases.h"
#include "SEVEN_D.h"
#include "SEVEN_E_aliases.h"
#include "SEVEN_E.h"
#include "SEVEN_F_aliases.h"
#include "SEVEN_F.h"
#include "SEVEN_G_aliases.h"
#include "SEVEN_G.h"
#include "SEVEN_DP_aliases.h"
#include "SEVEN_DP.h"
#include "SEVEN_SELECT_aliases.h"
#include "SEVEN_SELECT.h"
#include "SEVEN_reg.h"
#include "RED_LED_aliases.h"
#include "RED_LED.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "SI_aliases.h"
#include "SI.h"
#include "Clock_1.h"
#include "CS_aliases.h"
#include "CS.h"
#include "RS_aliases.h"
#include "RS.h"
#include "RST_aliases.h"
#include "RST.h"
#include "LED_aliases.h"
#include "LED.h"
#include "GREEN_LED_aliases.h"
#include "GREEN_LED.h"
#include "YELLOW_LED_aliases.h"
#include "YELLOW_LED.h"
#include "UART_LOG_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

